[project]
name = "mm-okx"
version = "0.3.3"
description = ""
requires-python = ">=3.13"
dependencies = [
    "mm-http~=0.1.1",
    "mm-print~=0.1.1",
    "pydantic>=2.11.7",
    "tomlkit~=0.13.3",
    "typer~=0.16.0",
]
[project.scripts]
mm-okx = "mm_okx.cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest~=8.4.1",
    "pytest-asyncio~=1.0.0",
    "pytest-xdist~=3.7.0",
    "mypy~=1.16.1",
    "ruff~=0.12.0",
    "pip-audit~=2.9.0",
    "bandit~=1.8.5",
    "pre-commit~=4.2.0",
    "python-dotenv>=1.1.1",
]

[tool.mypy]
python_version = "3.13"
warn_no_return = false
strict = true
exclude = ["^tests/", "^tmp/"]

[tool.ruff]
line-length = 130
target-version = "py313"
[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "TC", # flake8-type-checking, TYPE_CHECKING is dangerous, for example it doesn't work with pydantic
    "A005", # flake8-builtins: stdlib-module-shadowing
    "ERA001", # eradicate: commented-out-code
    "PT", # flake8-pytest-style
    "D", # pydocstyle
    "FIX", # flake8-fixme
    "PLR0911", # pylint: too-many-return-statements
    "PLR0912", # pylint: too-many-branches
    "PLR0913", # pylint: too-many-arguments
    "PLR2004", # pylint: magic-value-comparison
    "PLC0414", # pylint: useless-import-alias
    "FBT", # flake8-boolean-trap
    "EM", # flake8-errmsg
    "TRY003", # tryceratops: raise-vanilla-args
    "C901", # mccabe: complex-structure,
    "BLE001", # flake8-blind-except
    "S311", # bandit: suspicious-non-cryptographic-random-usage
    "TD002", # flake8-todos: missing-todo-author
    "TD003", # flake8-todos: missing-todo-link
    "RET503", # flake8-return: implicit-return
    "COM812", # it's used in ruff formatter
    "ASYNC109",
    "G004"
]
[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["field_validator"]
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["ANN", "S"]
[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B311"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
